### PR TITLE
fix(REACH-578): Update error message for shareGaInstance

### LINKED ISSUE #588: shareGaInstance not working with NextJs
Loading GA tag the proper way in NextJs and setting shareGaInstance prop gives this error: `Whoops! You enabled the shareGaInstance feature in yourtypeform embed but the tracker with ID G-CLB8J230JC was not found. Make sure to include Google Analytics Javascript code before the Typeform Embed Javascriptcode in your page and use correct tracker ID`

Google Analytics is loaded using Next's <Script> tag in _app.js, and the bundle including the npm package is loaded early on in the <Head>. I've tried to load the GA script earlier (which negatively affects the whole site) but still always get the same error.

I've also tried to Lazy load this library or via CDN script (so it loads after GA) but with no luck so far.

Has anyone managed to get this working with Next? it's a shame this is so fragile

### PR DESCRIPTION
**Pull request by mathio**
Inform developers their adblock might be preventing the Google Analytics from being loaded.

Resolves #588

The message is nicer now:
Screenshot 2023-07-07 at 10 37 04

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `70002825cbbf3ffca06e519f3d3131624b2a8828` [here](https://embed.typeform.com/70002825cbbf3ffca06e519f3d3131624b2a8828/embed.js).

File: packages/embed/src/utils/setup-google-analytics-instance.ts [hunk 1]
```diff
@@ -84,19 +83,10 @@ export const setupGaInstance = (iframe: HTMLIFrameElement, embedId: string, shar
...
-        )
+        logErrorMessage(`the tracker with ID ${trackingId} was not found`)
       }
     } catch (exception) {
-      logError(
-        'Whoops! You enabled the shareGaInstance feature in your typeform embed but the Google Analytics ' +
-          'object has not been found. Make sure to include Google Analytics Javascript code before the ' +
-          'Typeform Embed Javascript code in your page. '
-      )
+      logErrorMessage('the Google Analytics object has not been found')
```
Comment (leandro-serafim) [inline packages/embed/src/utils/setup-google-analytics-instance.ts:89]: Just to keep consistent with the other messages.
```suggestion
      logErrorMessage('the Google Analytics object was not found')
```

**Review by leandro-serafim — COMMENTED** [review]
Overall it looks good. Thanks.

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `f6ce150b512834fdcb8969263d3001379c814f5b` [here](https://embed.typeform.com/f6ce150b512834fdcb8969263d3001379c814f5b/embed.js).

**Review by mumpo — APPROVED** [review]
